server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/citi?serverTimezone=CTT&useSSL=false&characterEncoding=UTF-8
    username: root
    password: Tsc20010401
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:dataImpl/*Mapper.xml